### ISSUE TITLE
Clarification on Baseline AMOTA Discrepancies for ADA-Track with DETR3D and ResNet-101

### ISSUE THREAD

**Issue by sieafa** [dsx0511/ADA-Track#12]
Hi, thank you for your impressive work.

While recently reading [ADA-Track](https://arxiv.org/abs/2405.08909v1) and [ADA-Track++](https://arxiv.org/abs/2405.08909v2), as well as reviewing your [repository]([ADA-Track/README.md at main · dsx0511/ADA-Track](https://github.com/dsx0511/ADA-Track/blob/main/README.md?plain=1#L30)), I noticed some confusion regarding the baseline accuracy of _ADA-Track when using DETR3D and ResNet-101_. Specifically, the reported AMOTA values for the baselines are as follows:

1. [Repo Log]([ADA-Track/README.md at main · dsx0511/ADA-Track](https://github.com/dsx0511/ADA-Track/blob/main/README.md?plain=1#L30)): 0.384 AMOTA
2. [ADA-Track](https://arxiv.org/abs/2405.08909v1): 0.378 AMOTA
3. [ADA-Track++](https://arxiv.org/abs/2405.08909v2): 0.391 AMOTA

Although the differences between _the ADA-Track baseline_ and _the refined ADA-Track baseline_ are clarified in ADA-Track++, i.e., pre-trained model loading and the updated instance feature mechanism, there remains a discrepancy between the AMOTA values in 1 and 3. Could you kindly elaborate on the differences that account for this gap?

**Comment by dsx0511** [comment]
Hi @sieafa,

thank you for your interest in our recent extension paper! We achieved a performance gain from 0.378 AMOTA to 0.391 AMOTA by several bugs fixes and implementation improvements, where 
- the increase from 0.378 (cvpr version) to 0.384 (this repository) is caused by fixing pre-trained model loading and improved implementations, and 
- the increase from 0.384 (this repository) to 0.391 (ada-track++ arXiv paper) is achieved by the fixed instance feature update.
The fixes to achieve the former one has been already included in this repository, where the latter is currently unavailable due to an in-house code release approval. We will release them as soon as possible.

**Comment by sieafa** [comment]
Thank you for your clear and swift reply!
